version: '3.8'
services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - .:/aplicacao
    ports:
      - "3000:3000"
    depends_on:
      - db